jobmanager.rpc.address: flink-jobmanager
jobmanager.rpc.port: 6123
jobmanager.memory.process.size: 1600m
jobmanager.bind-host: 0.0.0.0

taskmanager.bind-host: 0.0.0.0
taskmanager.memory.process.size: 3200m
taskmanager.numberOfTaskSlots: 4

rest.address: flink-jobmanager
rest.port: 8081
rest.bind-address: 0.0.0.0

parallelism.default: 2
slot.request.timeout: 120000

blob.server.port: 6124
query.server.port: 6125

state.backend.type: filesystem
state.checkpoints.dir: file:///opt/flink/state/checkpoints
state.savepoints.dir: file:///opt/flink/state/savepoints

execution.checkpointing.interval: 60s
execution.checkpointing.min-pause: 30s
execution.checkpointing.tolerable-failed-checkpoints: 3

jobmanager.rpc.address=flink-jobmanager
taskmanager.numberOfTaskSlots=4
parallelism.default=2

